
# 工程名称
workspace "JKKit.xcworkspace"
# App工程名称
xcodeproj "JKKit.xcodeproj"

# 最低要求版本
platform :ios, "7.0"
# 去除pod库警告
#inhibit_all_warnings!

# 支持Swift (IOS8+才能用)
# use_frameworks!
    # 基础库（必备）

# pod库只存在当前目标
target :"JKKit_Example" do 
    pod 'JKKit' ,:path => '../'
    pod 'JKKit/Plugins' ,:path => '../'
    pod 'JKKit/Caches' ,:path => '../'
    pod 'JKKit/Refresh',:path => '../'
    pod 'JKKit/HUD',:path => '../'
    pod 'JKKit/Validator',:path => '../'
    pod 'JKKit/Security',:path => '../'

    target :"JKKit_Tests" do
      # 基础库（必备）
      inherit! :search_paths
    end
end

